server:
  port: 8083

spring:
       datasource:
         url: jdbc:mysql://localhost:3306/microservices
         username: root
         password: Root
         driver-class-name: com.mysql.cj.jdbc.Driver
       jpa:
         database-platform: org.hibernate.dialect.MySQL8Dialect
         hibernate:
           ddl-auto: create
         properties:
           hibernate:
             show_sql: true
             format_sql: true

       config:
         import: optional:configserver:http://localhost:8085

       security:
         oauth2:
           resourceserver:
             jwt:
               issuer-uri: https://dev-34423417.okta.com/oauth2/default
           client:
             registration:
               my-internal-client:
                 provider: okta
                 authorization-grant-type: client_credentials
                 scope: internal
                 client-id: 0oaapag1pwhKUeuI25d7
                 client-secret: htaN20Rlvlk3PN8A4vXWYJNAU_kXR2JOgThAgkIRqzK5WeGxuR3ouR1hPCGTncJm

             provider:
               okta:
                 issuer-uri: https://dev-34423417.okta.com/oauth2/default




management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
     instances:
       ratingHotelService:
         max-attempts: 3
         wait-duration: 5s





eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka



okta:
  oauth2:
    issuer: https://dev-34423417.okta.com/oauth2/default
    audience: api://default

